replicaCount: 2

image:
  repository: openresty/openresty
  tag: alpine
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: openresty.local
  path: /