replicaCount: 3

image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: nginx.local
  path: /