replicaCount: 1

image:
  repository: openresty/openresty
  tag: alpine
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  host: app.local
  path: /