apiVersion: v1
kind: Service
metadata:
  name: {{ include "openresty-art.fullname" . }}
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "openresty-art.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http